version: "2.1"

services:
  dkan_mariadb:
    image: wodby/mariadb:10.2-3.0.1
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: dkan
      MYSQL_USER: dkan
      MYSQL_PASSWORD: dkan
    healthcheck:
        test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
        timeout: 3s
        retries: 10

  dkan_memcached:
    image: wodby/memcached:1.4-2.0.0

  dkan_apache_php:
    build: .
    environment:
      DB_HOST: dkan_mariadb
      DB_DRIVER: mysql
      DB_USER: dkan
      DB_PASSWORD: dkan
      DB_NAME: dkan
      MEMCACHED_HOST: dkan_memcached
    depends_on:
      dkan_mariadb:
        condition: service_healthy
    ports:
      - "8787:80"
