version: '2.1'

services:
  dkan_apache_php:
    image: apache-php-fpm:latest
    environment:
      WWW_UID: 501
      WWW_GID: 501
    volumes:
      - dkan-starter-sync:/var/www/html:nocopy

volumes:
  dkan-starter-sync:
    external: true
